### ISSUE TITLE
Erreur lors de la mise à jour DYNDNS OVH

### ISSUE THREAD

**Issue by Ludos8** [RaspbianFrance/dyndnsovh#1]
Bonjour,

Depuis ce matin je rencontre un soucis, lorsque j'essaye de mettre à jour mon adresse IP sur OVH j'ai le message d'erreur suivant :
Adress n'est pas un IP

En cherchant un peu avec un amis, on a trouvé que la commande 👍 
PUBLIC_IP=$(host myip.opendns.com resolver1.opendns.com | grep "myip.opendns.com has" | awk '{print $4}')

Retourne une IPV6 et plus une IPV4.

**Comment by RaspbianFrance** [comment]
Merci de la remonté d'info, j'ai mis le script à jour pour forcer l'utilisation d'IPv4.
